version: "3.9"

services:
  db:
    image: postgres:15
    container_name: rpg_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpg
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  postgrest:
    image: postgrest/postgrest:v13.0.4
    container_name: rpg_postgrest
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/rpg
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_SERVER_PORT: 3000
      PGRST_OPENAPI_MODE: follow-privileges
      PGRST_OPENAPI_SERVER_PROD_URL: http://0.0.0.0:3000

  static:
    image: nginx:alpine
    volumes:
      - ./assets/icons/png:/usr/share/nginx/html:ro
    ports:
      - "4000:80"
