import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  map: { flex: 1 },
  statusHudContainer: {
    position: "absolute",
    top: 30,
    width: "30%",
    height: "10%",
    backgroundColor: "rgba(0, 0, 0, 0)",
    padding: 10,
  },
  selectedItemContainer: {
    backgroundColor: "#3a3835",
    borderWidth: 2,
    borderColor: "#6b4c35",
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    alignItems: "center",
  },
  selectedItemTitle: {
    fontSize: 20,
    fontFamily: "Cinzel-Bold",
    color: "#e6d3b3",
    marginBottom: 8,
  },
  selectedItemImage: {
    width: 100,
    height: 100,
    marginBottom: 8,
  },
  selectedItemDescription: {
    fontSize: 16,
    color: "#d7c4a3",
    marginBottom: 8,
    textAlign: "center",
  },
  selectedItemQuantity: {
    fontSize: 14,
    color: "#aaa",
    marginBottom: 8,
  },
  useButton: {
    backgroundColor: "#4CAF50",
    padding: 10,
    borderRadius: 8,
  },
  useButtonText: {
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
  },
  detailsHudContainer: {
    position: "absolute",
    top: 20,
    right: 20,
    width: "40%",
    backgroundColor: "rgba(20, 20, 20, 0.85)",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "rgba(180, 160, 100, 0.8)",
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.7,
    shadowOffset: { width: 4, height: 4 },
    shadowRadius: 6,
  },
  detailsHudTextName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#e0d6b4",
    marginBottom: 8,
  },
  detailsHudTextTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#d4c48f",
  },
  detailsHudTextStat: {
    fontSize: 13,
    color: "#c9c9c9",
    marginVertical: 1,
  },
  detailsHudDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
    marginVertical: 6,
  },
  weaponsHudContainer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: "24%",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    padding: 9,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  statText: {
    color: "#fff",
    fontSize: 16,
  },
  barContainer: {
    marginBottom: 10,
  },
  barLabel: {
    color: "#fff",
    fontSize: 14,
    marginBottom: 5,
  },
  barBackground: {
    width: "80%",
    height: 10,
    backgroundColor: "#777",
    borderRadius: 10,
    overflow: "hidden",
  },
  barFill: {
    height: "100%",
    borderRadius: 10,
  },
  slotsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  equipmentContainer: {
    position: "absolute",
    right: 10,
    bottom: "26%",
    flexDirection: "column",
    justifyContent: "space-around",
    gap: 10,
  },
  slotIcon: {
    width: 50,
    height: 50,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    padding: 20,
    justifyContent: "center",
  },
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 10,
    padding: 10,
  },
  section: { marginBottom: 20 },
  label: { fontSize: 16, fontWeight: "bold", marginBottom: 10 },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 10,
    fontSize: 16,
  },
  picker: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 10,
  },
  abilityRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  abilityLabel: { fontSize: 16, flex: 1 },
  characterCreationContainer: {
    flex: 1,
    backgroundColor: "#2b2a28",
  },
  title: {
    fontSize: 28,
    fontFamily: "Cinzel-Bold",
    color: "#f0e6d2",
    textAlign: "center",
    marginBottom: 20,
  },
  card: {
    backgroundColor: "#3a3835",
    borderWidth: 2,
    borderColor: "#6b4c35",
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  closeButton: {
    alignSelf: "flex-end",
    backgroundColor: "#6b4c35",
    padding: 10,
    borderRadius: 8,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 20,
    fontFamily: "Cinzel-Bold",
    color: "#e6d3b3",
    marginBottom: 8,
  },
  statBlock: {
    alignItems: "center",
    margin: 6,
    padding: 8,
    borderWidth: 1,
    borderColor: "#7a5e3a",
    borderRadius: 8,
    backgroundColor: "#2e2c29",
    minWidth: 60,
  },
  statLabel: {
    fontSize: 16,
    fontFamily: "Cinzel-Regular",
    color: "#d7c4a3",
  },
  statValue: {
    fontSize: 18,
    fontFamily: "Cinzel-Bold",
    color: "#fff",
  },
  skillTag: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    margin: 4,
    backgroundColor: "#554531",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#8a6e48",
  },
  skillText: {
    fontFamily: "Cinzel-Regular",
    fontSize: 16,
    color: "#f2e0c2",
  },
  dropdown: {
    flex: 1,
    marginHorizontal: 6,
  },
  dropdownLabel: {
    fontSize: 16,
    fontFamily: "Cinzel-Bold",
    color: "#d7c4a3",
  },
  dropdownValue: {
    fontSize: 16,
    fontFamily: "Cinzel-Regular",
    color: "#fff",
  },
  dropdownItem: {
    padding: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#6b4c35",
  },
  dropdownText: {
    fontFamily: "Cinzel-Regular",
    fontSize: 16,
    color: "#f2e0c2",
  },
  itemComparisonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  itemBlock: {
    flex: 1,
    backgroundColor: "rgba(40, 40, 40, 0.9)",
    margin: 4,
    padding: 8,
    borderRadius: 6,
    alignItems: "center",
  },
  blockTitle: {
    fontWeight: "bold",
    fontSize: 14,
    color: "gold",
    marginBottom: 4,
  },
  itemImage: {
    width: 64,
    height: 64,
    marginBottom: 4,
  },
  itemName: {
    fontWeight: "bold",
    color: "white",
    marginBottom: 4,
  },
  equipButton: {
    backgroundColor: "#6b4c35",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    marginTop: 10,
  },
  equipButtonText: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
  },
});
