/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 13.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AbilitiesRequiredItems,
} from '../models/index';
import {
    AbilitiesRequiredItemsFromJSON,
    AbilitiesRequiredItemsToJSON,
} from '../models/index';

export interface AbilitiesRequiredItemsDeleteRequest {
    abilityId?: string;
    itemTree?: string;
    requiredQuantity?: string;
    prefer?: AbilitiesRequiredItemsDeletePreferEnum;
}

export interface AbilitiesRequiredItemsGetRequest {
    abilityId?: string;
    itemTree?: string;
    requiredQuantity?: string;
    select?: string;
    order?: string;
    range?: string;
    rangeUnit?: string;
    offset?: string;
    limit?: string;
    prefer?: AbilitiesRequiredItemsGetPreferEnum;
}

export interface AbilitiesRequiredItemsPatchRequest {
    abilityId?: string;
    itemTree?: string;
    requiredQuantity?: string;
    prefer?: AbilitiesRequiredItemsPatchPreferEnum;
    abilitiesRequiredItems?: AbilitiesRequiredItems;
}

export interface AbilitiesRequiredItemsPostRequest {
    select?: string;
    prefer?: AbilitiesRequiredItemsPostPreferEnum;
    abilitiesRequiredItems?: AbilitiesRequiredItems;
}

/**
 * 
 */
export class AbilitiesRequiredItemsApi extends runtime.BaseAPI {

    /**
     */
    async abilitiesRequiredItemsDeleteRaw(requestParameters: AbilitiesRequiredItemsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['abilityId'] != null) {
            queryParameters['ability_id'] = requestParameters['abilityId'];
        }

        if (requestParameters['itemTree'] != null) {
            queryParameters['item_tree'] = requestParameters['itemTree'];
        }

        if (requestParameters['requiredQuantity'] != null) {
            queryParameters['required_quantity'] = requestParameters['requiredQuantity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/abilities_required_items`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async abilitiesRequiredItemsDelete(requestParameters: AbilitiesRequiredItemsDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.abilitiesRequiredItemsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async abilitiesRequiredItemsGetRaw(requestParameters: AbilitiesRequiredItemsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AbilitiesRequiredItems>>> {
        const queryParameters: any = {};

        if (requestParameters['abilityId'] != null) {
            queryParameters['ability_id'] = requestParameters['abilityId'];
        }

        if (requestParameters['itemTree'] != null) {
            queryParameters['item_tree'] = requestParameters['itemTree'];
        }

        if (requestParameters['requiredQuantity'] != null) {
            queryParameters['required_quantity'] = requestParameters['requiredQuantity'];
        }

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['range'] != null) {
            headerParameters['Range'] = String(requestParameters['range']);
        }

        if (requestParameters['rangeUnit'] != null) {
            headerParameters['Range-Unit'] = String(requestParameters['rangeUnit']);
        }

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/abilities_required_items`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AbilitiesRequiredItemsFromJSON));
    }

    /**
     */
    async abilitiesRequiredItemsGet(requestParameters: AbilitiesRequiredItemsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AbilitiesRequiredItems> | null | undefined > {
        const response = await this.abilitiesRequiredItemsGetRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 206:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     */
    async abilitiesRequiredItemsPatchRaw(requestParameters: AbilitiesRequiredItemsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['abilityId'] != null) {
            queryParameters['ability_id'] = requestParameters['abilityId'];
        }

        if (requestParameters['itemTree'] != null) {
            queryParameters['item_tree'] = requestParameters['itemTree'];
        }

        if (requestParameters['requiredQuantity'] != null) {
            queryParameters['required_quantity'] = requestParameters['requiredQuantity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/abilities_required_items`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AbilitiesRequiredItemsToJSON(requestParameters['abilitiesRequiredItems']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async abilitiesRequiredItemsPatch(requestParameters: AbilitiesRequiredItemsPatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.abilitiesRequiredItemsPatchRaw(requestParameters, initOverrides);
    }

    /**
     */
    async abilitiesRequiredItemsPostRaw(requestParameters: AbilitiesRequiredItemsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/abilities_required_items`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AbilitiesRequiredItemsToJSON(requestParameters['abilitiesRequiredItems']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async abilitiesRequiredItemsPost(requestParameters: AbilitiesRequiredItemsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.abilitiesRequiredItemsPostRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const AbilitiesRequiredItemsDeletePreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none'
} as const;
export type AbilitiesRequiredItemsDeletePreferEnum = typeof AbilitiesRequiredItemsDeletePreferEnum[keyof typeof AbilitiesRequiredItemsDeletePreferEnum];
/**
 * @export
 */
export const AbilitiesRequiredItemsGetPreferEnum = {
    Countnone: 'count=none'
} as const;
export type AbilitiesRequiredItemsGetPreferEnum = typeof AbilitiesRequiredItemsGetPreferEnum[keyof typeof AbilitiesRequiredItemsGetPreferEnum];
/**
 * @export
 */
export const AbilitiesRequiredItemsPatchPreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none'
} as const;
export type AbilitiesRequiredItemsPatchPreferEnum = typeof AbilitiesRequiredItemsPatchPreferEnum[keyof typeof AbilitiesRequiredItemsPatchPreferEnum];
/**
 * @export
 */
export const AbilitiesRequiredItemsPostPreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none',
    ResolutionignoreDuplicates: 'resolution=ignore-duplicates',
    ResolutionmergeDuplicates: 'resolution=merge-duplicates'
} as const;
export type AbilitiesRequiredItemsPostPreferEnum = typeof AbilitiesRequiredItemsPostPreferEnum[keyof typeof AbilitiesRequiredItemsPostPreferEnum];
