/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 13.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AbilitiesRequiredLevels,
} from '../models/index';
import {
    AbilitiesRequiredLevelsFromJSON,
    AbilitiesRequiredLevelsToJSON,
} from '../models/index';

export interface AbilitiesRequiredLevelsDeleteRequest {
    abilityId?: string;
    skillId?: string;
    requiredLevel?: string;
    prefer?: AbilitiesRequiredLevelsDeletePreferEnum;
}

export interface AbilitiesRequiredLevelsGetRequest {
    abilityId?: string;
    skillId?: string;
    requiredLevel?: string;
    select?: string;
    order?: string;
    range?: string;
    rangeUnit?: string;
    offset?: string;
    limit?: string;
    prefer?: AbilitiesRequiredLevelsGetPreferEnum;
}

export interface AbilitiesRequiredLevelsPatchRequest {
    abilityId?: string;
    skillId?: string;
    requiredLevel?: string;
    prefer?: AbilitiesRequiredLevelsPatchPreferEnum;
    abilitiesRequiredLevels?: AbilitiesRequiredLevels;
}

export interface AbilitiesRequiredLevelsPostRequest {
    select?: string;
    prefer?: AbilitiesRequiredLevelsPostPreferEnum;
    abilitiesRequiredLevels?: AbilitiesRequiredLevels;
}

/**
 * 
 */
export class AbilitiesRequiredLevelsApi extends runtime.BaseAPI {

    /**
     */
    async abilitiesRequiredLevelsDeleteRaw(requestParameters: AbilitiesRequiredLevelsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['abilityId'] != null) {
            queryParameters['ability_id'] = requestParameters['abilityId'];
        }

        if (requestParameters['skillId'] != null) {
            queryParameters['skill_id'] = requestParameters['skillId'];
        }

        if (requestParameters['requiredLevel'] != null) {
            queryParameters['required_level'] = requestParameters['requiredLevel'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/abilities_required_levels`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async abilitiesRequiredLevelsDelete(requestParameters: AbilitiesRequiredLevelsDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.abilitiesRequiredLevelsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async abilitiesRequiredLevelsGetRaw(requestParameters: AbilitiesRequiredLevelsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AbilitiesRequiredLevels>>> {
        const queryParameters: any = {};

        if (requestParameters['abilityId'] != null) {
            queryParameters['ability_id'] = requestParameters['abilityId'];
        }

        if (requestParameters['skillId'] != null) {
            queryParameters['skill_id'] = requestParameters['skillId'];
        }

        if (requestParameters['requiredLevel'] != null) {
            queryParameters['required_level'] = requestParameters['requiredLevel'];
        }

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['range'] != null) {
            headerParameters['Range'] = String(requestParameters['range']);
        }

        if (requestParameters['rangeUnit'] != null) {
            headerParameters['Range-Unit'] = String(requestParameters['rangeUnit']);
        }

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/abilities_required_levels`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AbilitiesRequiredLevelsFromJSON));
    }

    /**
     */
    async abilitiesRequiredLevelsGet(requestParameters: AbilitiesRequiredLevelsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AbilitiesRequiredLevels> | null | undefined > {
        const response = await this.abilitiesRequiredLevelsGetRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 206:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     */
    async abilitiesRequiredLevelsPatchRaw(requestParameters: AbilitiesRequiredLevelsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['abilityId'] != null) {
            queryParameters['ability_id'] = requestParameters['abilityId'];
        }

        if (requestParameters['skillId'] != null) {
            queryParameters['skill_id'] = requestParameters['skillId'];
        }

        if (requestParameters['requiredLevel'] != null) {
            queryParameters['required_level'] = requestParameters['requiredLevel'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/abilities_required_levels`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AbilitiesRequiredLevelsToJSON(requestParameters['abilitiesRequiredLevels']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async abilitiesRequiredLevelsPatch(requestParameters: AbilitiesRequiredLevelsPatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.abilitiesRequiredLevelsPatchRaw(requestParameters, initOverrides);
    }

    /**
     */
    async abilitiesRequiredLevelsPostRaw(requestParameters: AbilitiesRequiredLevelsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/abilities_required_levels`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AbilitiesRequiredLevelsToJSON(requestParameters['abilitiesRequiredLevels']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async abilitiesRequiredLevelsPost(requestParameters: AbilitiesRequiredLevelsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.abilitiesRequiredLevelsPostRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const AbilitiesRequiredLevelsDeletePreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none'
} as const;
export type AbilitiesRequiredLevelsDeletePreferEnum = typeof AbilitiesRequiredLevelsDeletePreferEnum[keyof typeof AbilitiesRequiredLevelsDeletePreferEnum];
/**
 * @export
 */
export const AbilitiesRequiredLevelsGetPreferEnum = {
    Countnone: 'count=none'
} as const;
export type AbilitiesRequiredLevelsGetPreferEnum = typeof AbilitiesRequiredLevelsGetPreferEnum[keyof typeof AbilitiesRequiredLevelsGetPreferEnum];
/**
 * @export
 */
export const AbilitiesRequiredLevelsPatchPreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none'
} as const;
export type AbilitiesRequiredLevelsPatchPreferEnum = typeof AbilitiesRequiredLevelsPatchPreferEnum[keyof typeof AbilitiesRequiredLevelsPatchPreferEnum];
/**
 * @export
 */
export const AbilitiesRequiredLevelsPostPreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none',
    ResolutionignoreDuplicates: 'resolution=ignore-duplicates',
    ResolutionmergeDuplicates: 'resolution=merge-duplicates'
} as const;
export type AbilitiesRequiredLevelsPostPreferEnum = typeof AbilitiesRequiredLevelsPostPreferEnum[keyof typeof AbilitiesRequiredLevelsPostPreferEnum];
