/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 13.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Classes,
} from '../models/index';
import {
    ClassesFromJSON,
    ClassesToJSON,
} from '../models/index';

export interface ClassesDeleteRequest {
    id?: string;
    name?: string;
    description?: string;
    bonusSpeed?: string;
    bonusHealth?: string;
    bonusMana?: string;
    bonusStrength?: string;
    bonusDexterity?: string;
    bonusIntelligence?: string;
    bonusCharisma?: string;
    bonusWisdom?: string;
    bonusConstitution?: string;
    bonusSkill?: string;
    image?: string;
    prefer?: ClassesDeletePreferEnum;
}

export interface ClassesGetRequest {
    id?: string;
    name?: string;
    description?: string;
    bonusSpeed?: string;
    bonusHealth?: string;
    bonusMana?: string;
    bonusStrength?: string;
    bonusDexterity?: string;
    bonusIntelligence?: string;
    bonusCharisma?: string;
    bonusWisdom?: string;
    bonusConstitution?: string;
    bonusSkill?: string;
    image?: string;
    select?: string;
    order?: string;
    range?: string;
    rangeUnit?: string;
    offset?: string;
    limit?: string;
    prefer?: ClassesGetPreferEnum;
}

export interface ClassesPatchRequest {
    id?: string;
    name?: string;
    description?: string;
    bonusSpeed?: string;
    bonusHealth?: string;
    bonusMana?: string;
    bonusStrength?: string;
    bonusDexterity?: string;
    bonusIntelligence?: string;
    bonusCharisma?: string;
    bonusWisdom?: string;
    bonusConstitution?: string;
    bonusSkill?: string;
    image?: string;
    prefer?: ClassesPatchPreferEnum;
    classes?: Classes;
}

export interface ClassesPostRequest {
    select?: string;
    prefer?: ClassesPostPreferEnum;
    classes?: Classes;
}

/**
 * 
 */
export class ClassesApi extends runtime.BaseAPI {

    /**
     */
    async classesDeleteRaw(requestParameters: ClassesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['description'] != null) {
            queryParameters['description'] = requestParameters['description'];
        }

        if (requestParameters['bonusSpeed'] != null) {
            queryParameters['bonus_speed'] = requestParameters['bonusSpeed'];
        }

        if (requestParameters['bonusHealth'] != null) {
            queryParameters['bonus_health'] = requestParameters['bonusHealth'];
        }

        if (requestParameters['bonusMana'] != null) {
            queryParameters['bonus_mana'] = requestParameters['bonusMana'];
        }

        if (requestParameters['bonusStrength'] != null) {
            queryParameters['bonus_strength'] = requestParameters['bonusStrength'];
        }

        if (requestParameters['bonusDexterity'] != null) {
            queryParameters['bonus_dexterity'] = requestParameters['bonusDexterity'];
        }

        if (requestParameters['bonusIntelligence'] != null) {
            queryParameters['bonus_intelligence'] = requestParameters['bonusIntelligence'];
        }

        if (requestParameters['bonusCharisma'] != null) {
            queryParameters['bonus_charisma'] = requestParameters['bonusCharisma'];
        }

        if (requestParameters['bonusWisdom'] != null) {
            queryParameters['bonus_wisdom'] = requestParameters['bonusWisdom'];
        }

        if (requestParameters['bonusConstitution'] != null) {
            queryParameters['bonus_constitution'] = requestParameters['bonusConstitution'];
        }

        if (requestParameters['bonusSkill'] != null) {
            queryParameters['bonus_skill'] = requestParameters['bonusSkill'];
        }

        if (requestParameters['image'] != null) {
            queryParameters['image'] = requestParameters['image'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/classes`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async classesDelete(requestParameters: ClassesDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.classesDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async classesGetRaw(requestParameters: ClassesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Classes>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['description'] != null) {
            queryParameters['description'] = requestParameters['description'];
        }

        if (requestParameters['bonusSpeed'] != null) {
            queryParameters['bonus_speed'] = requestParameters['bonusSpeed'];
        }

        if (requestParameters['bonusHealth'] != null) {
            queryParameters['bonus_health'] = requestParameters['bonusHealth'];
        }

        if (requestParameters['bonusMana'] != null) {
            queryParameters['bonus_mana'] = requestParameters['bonusMana'];
        }

        if (requestParameters['bonusStrength'] != null) {
            queryParameters['bonus_strength'] = requestParameters['bonusStrength'];
        }

        if (requestParameters['bonusDexterity'] != null) {
            queryParameters['bonus_dexterity'] = requestParameters['bonusDexterity'];
        }

        if (requestParameters['bonusIntelligence'] != null) {
            queryParameters['bonus_intelligence'] = requestParameters['bonusIntelligence'];
        }

        if (requestParameters['bonusCharisma'] != null) {
            queryParameters['bonus_charisma'] = requestParameters['bonusCharisma'];
        }

        if (requestParameters['bonusWisdom'] != null) {
            queryParameters['bonus_wisdom'] = requestParameters['bonusWisdom'];
        }

        if (requestParameters['bonusConstitution'] != null) {
            queryParameters['bonus_constitution'] = requestParameters['bonusConstitution'];
        }

        if (requestParameters['bonusSkill'] != null) {
            queryParameters['bonus_skill'] = requestParameters['bonusSkill'];
        }

        if (requestParameters['image'] != null) {
            queryParameters['image'] = requestParameters['image'];
        }

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['range'] != null) {
            headerParameters['Range'] = String(requestParameters['range']);
        }

        if (requestParameters['rangeUnit'] != null) {
            headerParameters['Range-Unit'] = String(requestParameters['rangeUnit']);
        }

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/classes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ClassesFromJSON));
    }

    /**
     */
    async classesGet(requestParameters: ClassesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Classes> | null | undefined > {
        const response = await this.classesGetRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 206:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     */
    async classesPatchRaw(requestParameters: ClassesPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['description'] != null) {
            queryParameters['description'] = requestParameters['description'];
        }

        if (requestParameters['bonusSpeed'] != null) {
            queryParameters['bonus_speed'] = requestParameters['bonusSpeed'];
        }

        if (requestParameters['bonusHealth'] != null) {
            queryParameters['bonus_health'] = requestParameters['bonusHealth'];
        }

        if (requestParameters['bonusMana'] != null) {
            queryParameters['bonus_mana'] = requestParameters['bonusMana'];
        }

        if (requestParameters['bonusStrength'] != null) {
            queryParameters['bonus_strength'] = requestParameters['bonusStrength'];
        }

        if (requestParameters['bonusDexterity'] != null) {
            queryParameters['bonus_dexterity'] = requestParameters['bonusDexterity'];
        }

        if (requestParameters['bonusIntelligence'] != null) {
            queryParameters['bonus_intelligence'] = requestParameters['bonusIntelligence'];
        }

        if (requestParameters['bonusCharisma'] != null) {
            queryParameters['bonus_charisma'] = requestParameters['bonusCharisma'];
        }

        if (requestParameters['bonusWisdom'] != null) {
            queryParameters['bonus_wisdom'] = requestParameters['bonusWisdom'];
        }

        if (requestParameters['bonusConstitution'] != null) {
            queryParameters['bonus_constitution'] = requestParameters['bonusConstitution'];
        }

        if (requestParameters['bonusSkill'] != null) {
            queryParameters['bonus_skill'] = requestParameters['bonusSkill'];
        }

        if (requestParameters['image'] != null) {
            queryParameters['image'] = requestParameters['image'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/classes`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ClassesToJSON(requestParameters['classes']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async classesPatch(requestParameters: ClassesPatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.classesPatchRaw(requestParameters, initOverrides);
    }

    /**
     */
    async classesPostRaw(requestParameters: ClassesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/classes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClassesToJSON(requestParameters['classes']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async classesPost(requestParameters: ClassesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.classesPostRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const ClassesDeletePreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none'
} as const;
export type ClassesDeletePreferEnum = typeof ClassesDeletePreferEnum[keyof typeof ClassesDeletePreferEnum];
/**
 * @export
 */
export const ClassesGetPreferEnum = {
    Countnone: 'count=none'
} as const;
export type ClassesGetPreferEnum = typeof ClassesGetPreferEnum[keyof typeof ClassesGetPreferEnum];
/**
 * @export
 */
export const ClassesPatchPreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none'
} as const;
export type ClassesPatchPreferEnum = typeof ClassesPatchPreferEnum[keyof typeof ClassesPatchPreferEnum];
/**
 * @export
 */
export const ClassesPostPreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none',
    ResolutionignoreDuplicates: 'resolution=ignore-duplicates',
    ResolutionmergeDuplicates: 'resolution=merge-duplicates'
} as const;
export type ClassesPostPreferEnum = typeof ClassesPostPreferEnum[keyof typeof ClassesPostPreferEnum];
