/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 13.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EnemyDrops,
} from '../models/index';
import {
    EnemyDropsFromJSON,
    EnemyDropsToJSON,
} from '../models/index';

export interface EnemyDropsDeleteRequest {
    enemyId?: string;
    itemId?: string;
    dropChance?: string;
    prefer?: EnemyDropsDeletePreferEnum;
}

export interface EnemyDropsGetRequest {
    enemyId?: string;
    itemId?: string;
    dropChance?: string;
    select?: string;
    order?: string;
    range?: string;
    rangeUnit?: string;
    offset?: string;
    limit?: string;
    prefer?: EnemyDropsGetPreferEnum;
}

export interface EnemyDropsPatchRequest {
    enemyId?: string;
    itemId?: string;
    dropChance?: string;
    prefer?: EnemyDropsPatchPreferEnum;
    enemyDrops?: EnemyDrops;
}

export interface EnemyDropsPostRequest {
    select?: string;
    prefer?: EnemyDropsPostPreferEnum;
    enemyDrops?: EnemyDrops;
}

/**
 * 
 */
export class EnemyDropsApi extends runtime.BaseAPI {

    /**
     */
    async enemyDropsDeleteRaw(requestParameters: EnemyDropsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['enemyId'] != null) {
            queryParameters['enemy_id'] = requestParameters['enemyId'];
        }

        if (requestParameters['itemId'] != null) {
            queryParameters['item_id'] = requestParameters['itemId'];
        }

        if (requestParameters['dropChance'] != null) {
            queryParameters['drop_chance'] = requestParameters['dropChance'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/enemy_drops`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async enemyDropsDelete(requestParameters: EnemyDropsDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.enemyDropsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async enemyDropsGetRaw(requestParameters: EnemyDropsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EnemyDrops>>> {
        const queryParameters: any = {};

        if (requestParameters['enemyId'] != null) {
            queryParameters['enemy_id'] = requestParameters['enemyId'];
        }

        if (requestParameters['itemId'] != null) {
            queryParameters['item_id'] = requestParameters['itemId'];
        }

        if (requestParameters['dropChance'] != null) {
            queryParameters['drop_chance'] = requestParameters['dropChance'];
        }

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['range'] != null) {
            headerParameters['Range'] = String(requestParameters['range']);
        }

        if (requestParameters['rangeUnit'] != null) {
            headerParameters['Range-Unit'] = String(requestParameters['rangeUnit']);
        }

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/enemy_drops`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EnemyDropsFromJSON));
    }

    /**
     */
    async enemyDropsGet(requestParameters: EnemyDropsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EnemyDrops> | null | undefined > {
        const response = await this.enemyDropsGetRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 206:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     */
    async enemyDropsPatchRaw(requestParameters: EnemyDropsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['enemyId'] != null) {
            queryParameters['enemy_id'] = requestParameters['enemyId'];
        }

        if (requestParameters['itemId'] != null) {
            queryParameters['item_id'] = requestParameters['itemId'];
        }

        if (requestParameters['dropChance'] != null) {
            queryParameters['drop_chance'] = requestParameters['dropChance'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/enemy_drops`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: EnemyDropsToJSON(requestParameters['enemyDrops']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async enemyDropsPatch(requestParameters: EnemyDropsPatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.enemyDropsPatchRaw(requestParameters, initOverrides);
    }

    /**
     */
    async enemyDropsPostRaw(requestParameters: EnemyDropsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/enemy_drops`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EnemyDropsToJSON(requestParameters['enemyDrops']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async enemyDropsPost(requestParameters: EnemyDropsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.enemyDropsPostRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const EnemyDropsDeletePreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none'
} as const;
export type EnemyDropsDeletePreferEnum = typeof EnemyDropsDeletePreferEnum[keyof typeof EnemyDropsDeletePreferEnum];
/**
 * @export
 */
export const EnemyDropsGetPreferEnum = {
    Countnone: 'count=none'
} as const;
export type EnemyDropsGetPreferEnum = typeof EnemyDropsGetPreferEnum[keyof typeof EnemyDropsGetPreferEnum];
/**
 * @export
 */
export const EnemyDropsPatchPreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none'
} as const;
export type EnemyDropsPatchPreferEnum = typeof EnemyDropsPatchPreferEnum[keyof typeof EnemyDropsPatchPreferEnum];
/**
 * @export
 */
export const EnemyDropsPostPreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none',
    ResolutionignoreDuplicates: 'resolution=ignore-duplicates',
    ResolutionmergeDuplicates: 'resolution=merge-duplicates'
} as const;
export type EnemyDropsPostPreferEnum = typeof EnemyDropsPostPreferEnum[keyof typeof EnemyDropsPostPreferEnum];
