/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 13.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Skills,
} from '../models/index';
import {
    SkillsFromJSON,
    SkillsToJSON,
} from '../models/index';

export interface SkillsDeleteRequest {
    id?: string;
    name?: string;
    description?: string;
    basePower?: string;
    prefer?: SkillsDeletePreferEnum;
}

export interface SkillsGetRequest {
    id?: string;
    name?: string;
    description?: string;
    basePower?: string;
    select?: string;
    order?: string;
    range?: string;
    rangeUnit?: string;
    offset?: string;
    limit?: string;
    prefer?: SkillsGetPreferEnum;
}

export interface SkillsPatchRequest {
    id?: string;
    name?: string;
    description?: string;
    basePower?: string;
    prefer?: SkillsPatchPreferEnum;
    skills?: Skills;
}

export interface SkillsPostRequest {
    select?: string;
    prefer?: SkillsPostPreferEnum;
    skills?: Skills;
}

/**
 * 
 */
export class SkillsApi extends runtime.BaseAPI {

    /**
     */
    async skillsDeleteRaw(requestParameters: SkillsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['description'] != null) {
            queryParameters['description'] = requestParameters['description'];
        }

        if (requestParameters['basePower'] != null) {
            queryParameters['base_power'] = requestParameters['basePower'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/skills`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async skillsDelete(requestParameters: SkillsDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.skillsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async skillsGetRaw(requestParameters: SkillsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Skills>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['description'] != null) {
            queryParameters['description'] = requestParameters['description'];
        }

        if (requestParameters['basePower'] != null) {
            queryParameters['base_power'] = requestParameters['basePower'];
        }

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['range'] != null) {
            headerParameters['Range'] = String(requestParameters['range']);
        }

        if (requestParameters['rangeUnit'] != null) {
            headerParameters['Range-Unit'] = String(requestParameters['rangeUnit']);
        }

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/skills`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SkillsFromJSON));
    }

    /**
     */
    async skillsGet(requestParameters: SkillsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Skills> | null | undefined > {
        const response = await this.skillsGetRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 206:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     */
    async skillsPatchRaw(requestParameters: SkillsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['description'] != null) {
            queryParameters['description'] = requestParameters['description'];
        }

        if (requestParameters['basePower'] != null) {
            queryParameters['base_power'] = requestParameters['basePower'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/skills`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SkillsToJSON(requestParameters['skills']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async skillsPatch(requestParameters: SkillsPatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.skillsPatchRaw(requestParameters, initOverrides);
    }

    /**
     */
    async skillsPostRaw(requestParameters: SkillsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['select'] != null) {
            queryParameters['select'] = requestParameters['select'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/skills`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SkillsToJSON(requestParameters['skills']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async skillsPost(requestParameters: SkillsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.skillsPostRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const SkillsDeletePreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none'
} as const;
export type SkillsDeletePreferEnum = typeof SkillsDeletePreferEnum[keyof typeof SkillsDeletePreferEnum];
/**
 * @export
 */
export const SkillsGetPreferEnum = {
    Countnone: 'count=none'
} as const;
export type SkillsGetPreferEnum = typeof SkillsGetPreferEnum[keyof typeof SkillsGetPreferEnum];
/**
 * @export
 */
export const SkillsPatchPreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none'
} as const;
export type SkillsPatchPreferEnum = typeof SkillsPatchPreferEnum[keyof typeof SkillsPatchPreferEnum];
/**
 * @export
 */
export const SkillsPostPreferEnum = {
    Returnrepresentation: 'return=representation',
    Returnminimal: 'return=minimal',
    Returnnone: 'return=none',
    ResolutionignoreDuplicates: 'resolution=ignore-duplicates',
    ResolutionmergeDuplicates: 'resolution=merge-duplicates'
} as const;
export type SkillsPostPreferEnum = typeof SkillsPostPreferEnum[keyof typeof SkillsPostPreferEnum];
