/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 13.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Classes
 */
export interface Classes {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * @type {number}
     * @memberof Classes
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Classes
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Classes
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Classes
     */
    bonusSpeed?: number;
    /**
     * 
     * @type {number}
     * @memberof Classes
     */
    bonusHealth?: number;
    /**
     * 
     * @type {number}
     * @memberof Classes
     */
    bonusMana?: number;
    /**
     * 
     * @type {number}
     * @memberof Classes
     */
    bonusStrength?: number;
    /**
     * 
     * @type {number}
     * @memberof Classes
     */
    bonusDexterity?: number;
    /**
     * 
     * @type {number}
     * @memberof Classes
     */
    bonusIntelligence?: number;
    /**
     * 
     * @type {number}
     * @memberof Classes
     */
    bonusCharisma?: number;
    /**
     * 
     * @type {number}
     * @memberof Classes
     */
    bonusWisdom?: number;
    /**
     * 
     * @type {number}
     * @memberof Classes
     */
    bonusConstitution?: number;
    /**
     * Note:
     * This is a Foreign Key to `skills.id`.<fk table='skills' column='id'/>
     * @type {number}
     * @memberof Classes
     */
    bonusSkill?: number;
    /**
     * 
     * @type {string}
     * @memberof Classes
     */
    image?: string;
}

/**
 * Check if a given object implements the Classes interface.
 */
export function instanceOfClasses(value: object): value is Classes {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ClassesFromJSON(json: any): Classes {
    return ClassesFromJSONTyped(json, false);
}

export function ClassesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Classes {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'bonusSpeed': json['bonus_speed'] == null ? undefined : json['bonus_speed'],
        'bonusHealth': json['bonus_health'] == null ? undefined : json['bonus_health'],
        'bonusMana': json['bonus_mana'] == null ? undefined : json['bonus_mana'],
        'bonusStrength': json['bonus_strength'] == null ? undefined : json['bonus_strength'],
        'bonusDexterity': json['bonus_dexterity'] == null ? undefined : json['bonus_dexterity'],
        'bonusIntelligence': json['bonus_intelligence'] == null ? undefined : json['bonus_intelligence'],
        'bonusCharisma': json['bonus_charisma'] == null ? undefined : json['bonus_charisma'],
        'bonusWisdom': json['bonus_wisdom'] == null ? undefined : json['bonus_wisdom'],
        'bonusConstitution': json['bonus_constitution'] == null ? undefined : json['bonus_constitution'],
        'bonusSkill': json['bonus_skill'] == null ? undefined : json['bonus_skill'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function ClassesToJSON(json: any): Classes {
    return ClassesToJSONTyped(json, false);
}

export function ClassesToJSONTyped(value?: Classes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'bonus_speed': value['bonusSpeed'],
        'bonus_health': value['bonusHealth'],
        'bonus_mana': value['bonusMana'],
        'bonus_strength': value['bonusStrength'],
        'bonus_dexterity': value['bonusDexterity'],
        'bonus_intelligence': value['bonusIntelligence'],
        'bonus_charisma': value['bonusCharisma'],
        'bonus_wisdom': value['bonusWisdom'],
        'bonus_constitution': value['bonusConstitution'],
        'bonus_skill': value['bonusSkill'],
        'image': value['image'],
    };
}

