/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 13.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnemyDrops
 */
export interface EnemyDrops {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `enemies.id`.<fk table='enemies' column='id'/>
     * @type {number}
     * @memberof EnemyDrops
     */
    enemyId: number;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `items.id`.<fk table='items' column='id'/>
     * @type {number}
     * @memberof EnemyDrops
     */
    itemId: number;
    /**
     * 
     * @type {number}
     * @memberof EnemyDrops
     */
    dropChance?: number;
}

/**
 * Check if a given object implements the EnemyDrops interface.
 */
export function instanceOfEnemyDrops(value: object): value is EnemyDrops {
    if (!('enemyId' in value) || value['enemyId'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    return true;
}

export function EnemyDropsFromJSON(json: any): EnemyDrops {
    return EnemyDropsFromJSONTyped(json, false);
}

export function EnemyDropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnemyDrops {
    if (json == null) {
        return json;
    }
    return {
        
        'enemyId': json['enemy_id'],
        'itemId': json['item_id'],
        'dropChance': json['drop_chance'] == null ? undefined : json['drop_chance'],
    };
}

export function EnemyDropsToJSON(json: any): EnemyDrops {
    return EnemyDropsToJSONTyped(json, false);
}

export function EnemyDropsToJSONTyped(value?: EnemyDrops | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enemy_id': value['enemyId'],
        'item_id': value['itemId'],
        'drop_chance': value['dropChance'],
    };
}

