/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 13.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Items
 */
export interface Items {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * @type {number}
     * @memberof Items
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Items
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Items
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Items
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof Items
     */
    mana?: number;
    /**
     * 
     * @type {string}
     * @memberof Items
     */
    equipmentSlot?: string;
    /**
     * 
     * @type {number}
     * @memberof Items
     */
    bonusDamage?: number;
    /**
     * 
     * @type {number}
     * @memberof Items
     */
    bonusDamageChange?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Items
     */
    repairable?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Items
     */
    durability?: number;
    /**
     * 
     * @type {number}
     * @memberof Items
     */
    armorClass?: number;
    /**
     * 
     * @type {number}
     * @memberof Items
     */
    armorSlots?: number;
    /**
     * 
     * @type {number}
     * @memberof Items
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof Items
     */
    goldValue?: number;
    /**
     * 
     * @type {string}
     * @memberof Items
     */
    tree?: string;
    /**
     * 
     * @type {string}
     * @memberof Items
     */
    image?: string;
}

/**
 * Check if a given object implements the Items interface.
 */
export function instanceOfItems(value: object): value is Items {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ItemsFromJSON(json: any): Items {
    return ItemsFromJSONTyped(json, false);
}

export function ItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Items {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'mana': json['mana'] == null ? undefined : json['mana'],
        'equipmentSlot': json['equipment_slot'] == null ? undefined : json['equipment_slot'],
        'bonusDamage': json['bonus_damage'] == null ? undefined : json['bonus_damage'],
        'bonusDamageChange': json['bonus_damage_change'] == null ? undefined : json['bonus_damage_change'],
        'repairable': json['repairable'] == null ? undefined : json['repairable'],
        'durability': json['durability'] == null ? undefined : json['durability'],
        'armorClass': json['armor_class'] == null ? undefined : json['armor_class'],
        'armorSlots': json['armor_slots'] == null ? undefined : json['armor_slots'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'goldValue': json['gold_value'] == null ? undefined : json['gold_value'],
        'tree': json['tree'] == null ? undefined : json['tree'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function ItemsToJSON(json: any): Items {
    return ItemsToJSONTyped(json, false);
}

export function ItemsToJSONTyped(value?: Items | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'mana': value['mana'],
        'equipment_slot': value['equipmentSlot'],
        'bonus_damage': value['bonusDamage'],
        'bonus_damage_change': value['bonusDamageChange'],
        'repairable': value['repairable'],
        'durability': value['durability'],
        'armor_class': value['armorClass'],
        'armor_slots': value['armorSlots'],
        'weight': value['weight'],
        'gold_value': value['goldValue'],
        'tree': value['tree'],
        'image': value['image'],
    };
}

