/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 13.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Items
 */
export interface Items {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * @type {number}
     * @memberof Items
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Items
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Items
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Items
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof Items
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof Items
     */
    image?: string;
}

/**
 * Check if a given object implements the Items interface.
 */
export function instanceOfItems(value: object): value is Items {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ItemsFromJSON(json: any): Items {
    return ItemsFromJSONTyped(json, false);
}

export function ItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Items {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function ItemsToJSON(json: any): Items {
    return ItemsToJSONTyped(json, false);
}

export function ItemsToJSONTyped(value?: Items | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'weight': value['weight'],
        'image': value['image'],
    };
}

